name: "bashtest"

on:
  workflow_dispatch:
    inputs:
      secret_input:
        description: This is a secret
        required: true

jobs:
  Test_Bash:
    runs-on: ubuntu-latest
    steps:
      - name: TestBash
        shell: bash
        run: |
          echo $SECRET_VALUE
        env:
          SECRET_VALUE: ${{secrets[github.event.inputs.secret_input]}}
    
