name: "NonProd_Deploy"

on:
  push:
    paths:
      - gitflowterraform/**
      - config/nonprod_backend.yml
      - .github/workflows/nonprod_deploy.yml
    branches:
      - main

  pull_request:
    paths:
      - gitflowterraform/**
      - config/nonprod_backend.yml
      - .github/workflows/nonprod_deploy.yml
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    uses: Oddjob62/gitflowtest/.github/workflows/run_terraform.yml@main
    with:
      environment: NONPROD
      config: nonprod
      working_directory: gitflowterraform

    secrets: inherit