name: "NonProd_Deploy"

on:
  push:
    paths:
      - terraform/**
      - config/nonprod_backend.yml
      - .github/workflows/nonprod_deploy.yml
    branches:
      - nonprod

  pull_request:
    paths:
      - terraform/**
      - config/nonprod_backend.yml
      - .github/workflows/nonprod_deploy.yml
    branches:
      - nonprod

  workflow_dispatch:

jobs:
  deploy:
    uses: Oddjob62/gitflowtest/.github/workflows/run_terraform.yml@main
    with:
      environment: NONPROD
    secrets: inherit