name: "Prod_Deploy"

on:
  [push, pull_request]:
    paths:
      - terraform/**
      - config/prod_backend.yml
  workflow_dispatch:

jobs:
  deploy:
    steps:
      if: github.event_name == 'pull_request'
      uses: Oddjob62/gitflowtest/.github/workflows/run_terraform.yml@main
      with:
        environment: PROD
      secrets: inherit