name: "Prod_Deploy"

on:
  push:
    paths:
      - gitflowterraform/**
      - config/prod_backend.yml
      - .github/workflows/prod_deploy.yml
    branches:
      - main
  pull_request:
    paths:
      - gitflowterraform/**
      - config/prod_backend.yml
      - .github/workflows/prod_deploy.yml
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: Oddjob62/gitflowtest/.github/workflows/run_terraform.yml@main
    with:
      environment: PROD
      config: prod
      working_directory: gitflowterraform
    secrets: inherit