name: "Prod_Deploy"

on:
  push:
    paths:
      - terraform/**
      - config/prod_backend.yml
      - .github/workflow/prod.depoy.yml
  pull_request:
    paths:
      - terraform/**
      - config/prod_backend.yml
  workflow_dispatch:

jobs:
  deploy:
    uses: Oddjob62/gitflowtest/.github/workflows/run_terraform.yml@main
    with:
      environment: PROD
    secrets: inherit