name: "testworkflow"

on:
  workflow_dispatch:
    inputs:
      enable_ssh:
        type: boolean
        required: false
        default: false

jobs:
  Test_Bash:
    runs-on: ubuntu-latest
    steps:
      - name: TestStep
        shell: bash
        run: |
          RUNNER_TEMP="./"
          if ${{ inputs.enable_ssh }}
          then
          # cloud init script to register runner with GH
          START_SCRIPT=$RUNNER_TEMP/init.txt
          cat <<EOT > $START_SCRIPT
          #!/bin/bash
          echo starting
          sudo -i -u runner bash << EOF
          cd ~
          cd actions-runner
          ./config.sh --unattended --url https://github.com/enterprises/123 --token 123 --labels !23 --runnergroup 123
          sudo ./svc.sh install
          sudo ./svc.sh start
          EOF
          EOT
          else
          # cloud init script to register runner with GH
          START_SCRIPT=$RUNNER_TEMP/init.txt
          cat <<EOT > $START_SCRIPT
          #!/bin/bash
          echo starting
          sudo -i -u runner bash << EOF
          cd ~
          cd actions-runner
          ./config.sh --unattended --url https://github.com/enterprises/123 --token 123 --labels 123 --runnergroup 123
          sudo ./svc.sh install
          sudo ./svc.sh start
          sudo apt -y remove walinuxagent
          sudo apt -y remove openssh-client
          EOF
          EOT
          fi

          ls -l

          cat $RUNNER_TEMP/init.txt