name: "testworkflow"

on:
  workflow_dispatch:
    inputs:
      disable_ssh:
        type: boolean
        required: false
        default: true

jobs:
  Test_Bash:
    runs-on: ubuntu-latest
    steps:
      - name: TestStep
        shell: bash
        run: |
          if [[ "${{ inputs.disable_ssh }}" ]]
          then
            echo "Disable SSH"
          else
            echo "Do NOT disable SSH"
          fi
