name: "testworkflow"

on:
  workflow_dispatch:
    inputs:
      enable_ssh:
        type: boolean
        required: false
        default: false

jobs:
  Test_Bash:
    runs-on: ubuntu-latest
    steps:
      - name: TestStep
        shell: bash
        run: |
          if ${{ inputs.enable_ssh }}
          then
            echo "Enable SSH"
          else
            echo "Disable SSH"
          fi
