name: "Test_Linux_VM"

on:
  workflow_dispatch:
    inputs: 
      vm_name:
        description: Name of Virtual Machine
        required: true
        type: string
      public_key:
        required: true
        type: string


jobs:
  Create_Virtual_Machine:
    runs-on: ubuntu-latest

      env:
        ARM_CLIENT_ID: ${{ secrets.APPID }}
        ARM_CLIENT_SECRET: ${{ secrets.PASSWORD }}
        ARM_TENANT_ID: "9c29d70b-9e7a-44d5-abe2-7e53df86502f"
        ARM_SUBSCRIPTION_ID: "ff65e97e-c6be-4f35-b6b7-e52ce88bf5b2"
        ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}
        working-directory: ./test_linux_vm

    steps:

    - name: testoutput
      run: |
        echo ${{ env.working-directory }}/../config/${{ inputs.environment }}_backend.tf

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.appId }}","clientSecret":"${{ secrets.password }}","subscriptionId":"ff65e97e-c6be-4f35-b6b7-e52ce88bf5b2","tenantId":"9c29d70b-9e7a-44d5-abe2-7e53df86502f"}'
    
    - uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v1
        
    - name: terraform-init
      id: terraform
      run: |
        cd ${{ env.working-directory }}
        terraform init 
        terraform apply auto-approve